import {
  AlertCircle,
  AlertTriangle,
  Anchor,
  Archive,
  BarChart3,
  Bell,
  Bluetooth,
  Book,
  BookOpen,
  Boxes,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Camera,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudCog,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Download,
  Eye,
  EyeOff,
  Factory,
  FileSpreadsheet,
  FileText,
  Filter,
  Flag,
  Folder,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  Globe,
  Grid3x3,
  Hammer,
  Handshake,
  HardDrive,
  Home,
  Image as ImageIconLucide,
  Inbox,
  Info,
  Key,
  Laptop,
  Layers,
  LayoutGrid,
  LineChart,
  Link2,
  List,
  Lock,
  Map,
  MapPin,
  Mail,
  Monitor,
  Navigation,
  Package,
  Package2,
  PhoneCall,
  PieChart,
  Printer,
  RefreshCw,
  Route,
  Router,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Signal,
  SlidersHorizontal,
  Smartphone,
  Star,
  Tablet,
  Target,
  Terminal,
  Timer,
  Plane,
  Truck,
  TrendingUp,
  Unlock,
  Users,
  User,
  UserCheck,
  Warehouse,
  Webcam,
  Wifi,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

import type { IconComponent } from "../lib/iconToDataUrl";
import {
  IconApiGateway,
  IconCloudFront,
  IconCloudWatch,
  IconDynamoDb,
  IconEc2,
  IconEcs,
  IconElastiCache,
  IconElb,
  IconIam,
  IconLambda,
  IconRds,
  IconRoute53,
  IconS3,
  IconSns,
  IconSqs,
  IconVpc,
} from "./awsIcons";

export interface IconAsset {
  key: string;
  label: string;
  keywords: string[];
  Icon: IconComponent;
  category: "business" | "it" | "data" | "logistics" | "general" | "cloud";
}

/** A searchable icon catalog for the Assets panel — pulled from lucide-react
 *  (the same stroke family this app's own hand-drawn icons already imitate),
 *  curated down to what's actually relevant across the diagram categories
 *  this app already has (business/it/data/project/logistics) rather than
 *  the full ~1500-icon set, which would make search noisy more than useful. */
export const ICON_CATALOG: IconAsset[] = [
  // business
  { key: "briefcase", label: "Briefcase", keywords: ["work", "job", "business"], Icon: Briefcase, category: "business" },
  { key: "building", label: "Building", keywords: ["office", "company"], Icon: Building, category: "business" },
  { key: "building-2", label: "Office tower", keywords: ["office", "hq", "headquarters"], Icon: Building2, category: "business" },
  { key: "handshake", label: "Handshake", keywords: ["deal", "partnership", "agreement"], Icon: Handshake, category: "business" },
  { key: "target", label: "Target", keywords: ["goal", "objective", "kpi"], Icon: Target, category: "business" },
  { key: "trending-up", label: "Trending up", keywords: ["growth", "chart", "sales"], Icon: TrendingUp, category: "business" },
  { key: "credit-card", label: "Payment", keywords: ["credit card", "billing", "finance"], Icon: CreditCard, category: "business" },
  { key: "users", label: "Team", keywords: ["people", "group", "users"], Icon: Users, category: "business" },
  { key: "user", label: "Person", keywords: ["user", "actor", "customer"], Icon: User, category: "business" },
  { key: "user-check", label: "Approved user", keywords: ["verified", "approved", "account"], Icon: UserCheck, category: "business" },
  { key: "calendar", label: "Calendar", keywords: ["date", "schedule", "deadline"], Icon: Calendar, category: "business" },
  { key: "clipboard-list", label: "Checklist", keywords: ["task", "todo", "requirements"], Icon: ClipboardList, category: "business" },
  { key: "clipboard-check", label: "Approved checklist", keywords: ["approved", "signoff", "audit"], Icon: ClipboardCheck, category: "business" },
  { key: "mail", label: "Email", keywords: ["mail", "message", "notification"], Icon: Mail, category: "business" },
  { key: "phone-call", label: "Phone call", keywords: ["call", "contact", "support"], Icon: PhoneCall, category: "business" },
  { key: "workflow", label: "Workflow", keywords: ["process", "pipeline", "steps"], Icon: Workflow, category: "business" },

  // it / infrastructure
  { key: "cloud", label: "Cloud", keywords: ["cloud", "saas", "hosting"], Icon: Cloud, category: "it" },
  { key: "cloud-cog", label: "Cloud service", keywords: ["cloud", "config", "iaas"], Icon: CloudCog, category: "it" },
  { key: "server", label: "Server", keywords: ["backend", "host", "compute"], Icon: Server, category: "it" },
  { key: "database", label: "Database", keywords: ["db", "storage", "sql"], Icon: Database, category: "it" },
  { key: "hard-drive", label: "Storage", keywords: ["disk", "storage", "volume"], Icon: HardDrive, category: "it" },
  { key: "cpu", label: "Processor", keywords: ["cpu", "compute", "chip"], Icon: Cpu, category: "it" },
  { key: "wifi", label: "Wi-Fi", keywords: ["network", "wireless", "internet"], Icon: Wifi, category: "it" },
  { key: "router", label: "Router", keywords: ["network", "gateway", "switch"], Icon: Router, category: "it" },
  { key: "shield", label: "Security", keywords: ["security", "protection", "firewall"], Icon: Shield, category: "it" },
  { key: "shield-check", label: "Verified security", keywords: ["compliant", "secure", "verified"], Icon: ShieldCheck, category: "it" },
  { key: "key", label: "Auth key", keywords: ["auth", "access", "credential"], Icon: Key, category: "it" },
  { key: "lock", label: "Locked", keywords: ["secure", "private", "restricted"], Icon: Lock, category: "it" },
  { key: "unlock", label: "Unlocked", keywords: ["public", "open", "access"], Icon: Unlock, category: "it" },
  { key: "terminal", label: "Terminal", keywords: ["cli", "shell", "console"], Icon: Terminal, category: "it" },
  { key: "laptop", label: "Laptop", keywords: ["device", "computer", "client"], Icon: Laptop, category: "it" },
  { key: "monitor", label: "Desktop", keywords: ["screen", "display", "workstation"], Icon: Monitor, category: "it" },
  { key: "smartphone", label: "Mobile", keywords: ["phone", "app", "device"], Icon: Smartphone, category: "it" },
  { key: "tablet", label: "Tablet", keywords: ["device", "ipad"], Icon: Tablet, category: "it" },
  { key: "printer", label: "Printer", keywords: ["print", "output", "device"], Icon: Printer, category: "it" },
  { key: "webcam", label: "Camera device", keywords: ["webcam", "video", "iot"], Icon: Webcam, category: "it" },
  { key: "bluetooth", label: "Bluetooth", keywords: ["wireless", "pairing"], Icon: Bluetooth, category: "it" },
  { key: "signal", label: "Signal", keywords: ["network", "connectivity", "strength"], Icon: Signal, category: "it" },
  { key: "refresh-cw", label: "Sync", keywords: ["sync", "refresh", "update"], Icon: RefreshCw, category: "it" },
  { key: "zap", label: "Trigger", keywords: ["event", "webhook", "automation"], Icon: Zap, category: "it" },

  // data
  { key: "bar-chart", label: "Bar chart", keywords: ["chart", "analytics", "report"], Icon: BarChart3, category: "data" },
  { key: "line-chart", label: "Line chart", keywords: ["chart", "trend", "metrics"], Icon: LineChart, category: "data" },
  { key: "pie-chart", label: "Pie chart", keywords: ["chart", "breakdown", "share"], Icon: PieChart, category: "data" },
  { key: "file-spreadsheet", label: "Spreadsheet", keywords: ["excel", "csv", "table"], Icon: FileSpreadsheet, category: "data" },
  { key: "filter", label: "Filter", keywords: ["filter", "query", "validation"], Icon: Filter, category: "data" },
  { key: "layers", label: "Layers", keywords: ["stack", "pipeline", "tiers"], Icon: Layers, category: "data" },
  { key: "git-branch", label: "Branch", keywords: ["version", "fork", "split"], Icon: GitBranch, category: "data" },
  { key: "git-merge", label: "Merge", keywords: ["merge", "combine", "join"], Icon: GitMerge, category: "data" },
  { key: "git-commit", label: "Commit", keywords: ["version", "checkpoint"], Icon: GitCommit, category: "data" },
  { key: "grid", label: "Grid", keywords: ["table", "matrix", "dataset"], Icon: Grid3x3, category: "data" },
  { key: "layout-grid", label: "Dashboard", keywords: ["dashboard", "widgets", "layout"], Icon: LayoutGrid, category: "data" },
  { key: "list", label: "List", keywords: ["list", "records", "rows"], Icon: List, category: "data" },
  { key: "sliders", label: "Controls", keywords: ["settings", "parameters", "tuning"], Icon: SlidersHorizontal, category: "data" },

  // logistics
  { key: "truck", label: "Truck", keywords: ["delivery", "freight", "transport"], Icon: Truck, category: "logistics" },
  { key: "ship", label: "Ship", keywords: ["sea freight", "cargo", "vessel"], Icon: Ship, category: "logistics" },
  { key: "plane", label: "Plane", keywords: ["air freight", "flight", "shipping"], Icon: Plane, category: "logistics" },
  { key: "package", label: "Package", keywords: ["parcel", "shipment", "box"], Icon: Package, category: "logistics" },
  { key: "package-2", label: "Crate", keywords: ["box", "cargo", "goods"], Icon: Package2, category: "logistics" },
  { key: "boxes", label: "Inventory", keywords: ["stock", "warehouse", "boxes"], Icon: Boxes, category: "logistics" },
  { key: "warehouse", label: "Warehouse", keywords: ["storage", "distribution centre"], Icon: Warehouse, category: "logistics" },
  { key: "factory", label: "Factory", keywords: ["manufacturing", "plant", "production"], Icon: Factory, category: "logistics" },
  { key: "anchor", label: "Port", keywords: ["harbour", "dock", "sea"], Icon: Anchor, category: "logistics" },
  { key: "map-pin", label: "Location", keywords: ["pin", "address", "destination"], Icon: MapPin, category: "logistics" },
  { key: "navigation", label: "Route", keywords: ["gps", "direction", "tracking"], Icon: Navigation, category: "logistics" },
  { key: "route", label: "Path", keywords: ["route", "journey", "path"], Icon: Route, category: "logistics" },
  { key: "compass", label: "Compass", keywords: ["direction", "navigation"], Icon: Compass, category: "logistics" },
  { key: "map", label: "Map", keywords: ["map", "area", "region"], Icon: Map, category: "logistics" },
  { key: "shopping-cart", label: "Order", keywords: ["cart", "purchase", "ecommerce"], Icon: ShoppingCart, category: "logistics" },

  // general / ui
  { key: "check-circle", label: "Success", keywords: ["done", "complete", "approved"], Icon: CheckCircle2, category: "general" },
  { key: "alert-triangle", label: "Warning", keywords: ["risk", "caution", "issue"], Icon: AlertTriangle, category: "general" },
  { key: "alert-circle", label: "Error", keywords: ["error", "problem", "failure"], Icon: AlertCircle, category: "general" },
  { key: "info", label: "Info", keywords: ["info", "note", "details"], Icon: Info, category: "general" },
  { key: "star", label: "Star", keywords: ["favourite", "rating", "featured"], Icon: Star, category: "general" },
  { key: "flag", label: "Flag", keywords: ["milestone", "marker", "country"], Icon: Flag, category: "general" },
  { key: "bell", label: "Notification", keywords: ["alert", "reminder", "notify"], Icon: Bell, category: "general" },
  { key: "settings", label: "Settings", keywords: ["config", "preferences", "gear"], Icon: Settings, category: "general" },
  { key: "search", label: "Search", keywords: ["find", "lookup", "query"], Icon: Search, category: "general" },
  { key: "link", label: "Link", keywords: ["url", "connection", "reference"], Icon: Link2, category: "general" },
  { key: "share", label: "Share", keywords: ["share", "distribute", "broadcast"], Icon: Share2, category: "general" },
  { key: "download", label: "Download", keywords: ["download", "export", "save"], Icon: Download, category: "general" },
  { key: "folder", label: "Folder", keywords: ["directory", "files", "storage"], Icon: Folder, category: "general" },
  { key: "archive", label: "Archive", keywords: ["archive", "storage", "backup"], Icon: Archive, category: "general" },
  { key: "inbox", label: "Inbox", keywords: ["queue", "incoming", "messages"], Icon: Inbox, category: "general" },
  { key: "send", label: "Send", keywords: ["submit", "dispatch", "outbound"], Icon: Send, category: "general" },
  { key: "globe", label: "Globe", keywords: ["global", "internet", "world"], Icon: Globe, category: "general" },
  { key: "home", label: "Home", keywords: ["home", "start", "main"], Icon: Home, category: "general" },
  { key: "gift", label: "Reward", keywords: ["gift", "reward", "incentive"], Icon: Gift, category: "general" },
  { key: "eye", label: "Visible", keywords: ["view", "visible", "show"], Icon: Eye, category: "general" },
  { key: "eye-off", label: "Hidden", keywords: ["hide", "private", "invisible"], Icon: EyeOff, category: "general" },
  { key: "clock", label: "Time", keywords: ["time", "duration", "history"], Icon: Clock, category: "general" },
  { key: "timer", label: "Timer", keywords: ["countdown", "deadline", "sla"], Icon: Timer, category: "general" },
  { key: "camera", label: "Camera", keywords: ["photo", "capture", "media"], Icon: Camera, category: "general" },
  { key: "image", label: "Image", keywords: ["picture", "photo", "media"], Icon: ImageIconLucide, category: "general" },
  { key: "file-text", label: "Document", keywords: ["file", "report", "text"], Icon: FileText, category: "general" },
  { key: "book", label: "Book", keywords: ["docs", "manual", "reference"], Icon: Book, category: "general" },
  { key: "book-open", label: "Guide", keywords: ["docs", "reading", "handbook"], Icon: BookOpen, category: "general" },
  { key: "wrench", label: "Maintenance", keywords: ["tool", "fix", "config"], Icon: Wrench, category: "general" },
  { key: "hammer", label: "Build", keywords: ["build", "construct", "tool"], Icon: Hammer, category: "general" },

  // cloud / AWS-style — coloured badges (drawn from scratch, not AWS's own
  // artwork) so architecture diagrams can name the actual service instead of
  // a generic "server" or "database" box.
  { key: "aws-ec2", label: "EC2 instance", keywords: ["aws", "compute", "vm", "server"], Icon: IconEc2, category: "cloud" },
  { key: "aws-lambda", label: "Lambda", keywords: ["aws", "serverless", "function"], Icon: IconLambda, category: "cloud" },
  { key: "aws-ecs", label: "ECS / containers", keywords: ["aws", "docker", "container", "kubernetes"], Icon: IconEcs, category: "cloud" },
  { key: "aws-s3", label: "S3 bucket", keywords: ["aws", "storage", "bucket", "object storage"], Icon: IconS3, category: "cloud" },
  { key: "aws-rds", label: "RDS database", keywords: ["aws", "database", "sql", "mysql", "postgres"], Icon: IconRds, category: "cloud" },
  { key: "aws-dynamodb", label: "DynamoDB", keywords: ["aws", "nosql", "database"], Icon: IconDynamoDb, category: "cloud" },
  { key: "aws-elasticache", label: "ElastiCache / Redis", keywords: ["aws", "cache", "redis", "memcached"], Icon: IconElastiCache, category: "cloud" },
  { key: "aws-route53", label: "Route 53", keywords: ["aws", "dns", "domain", "routing"], Icon: IconRoute53, category: "cloud" },
  { key: "aws-elb", label: "Load balancer", keywords: ["aws", "elb", "alb", "load balancing"], Icon: IconElb, category: "cloud" },
  { key: "aws-cloudfront", label: "CloudFront", keywords: ["aws", "cdn", "edge", "cache"], Icon: IconCloudFront, category: "cloud" },
  { key: "aws-api-gateway", label: "API Gateway", keywords: ["aws", "api", "rest", "gateway"], Icon: IconApiGateway, category: "cloud" },
  { key: "aws-vpc", label: "VPC", keywords: ["aws", "network", "subnet", "vpc"], Icon: IconVpc, category: "cloud" },
  { key: "aws-iam", label: "IAM", keywords: ["aws", "identity", "access", "permissions"], Icon: IconIam, category: "cloud" },
  { key: "aws-sqs", label: "SQS queue", keywords: ["aws", "queue", "messaging"], Icon: IconSqs, category: "cloud" },
  { key: "aws-sns", label: "SNS topic", keywords: ["aws", "notification", "pub/sub", "messaging"], Icon: IconSns, category: "cloud" },
  { key: "aws-cloudwatch", label: "CloudWatch", keywords: ["aws", "monitoring", "logs", "metrics"], Icon: IconCloudWatch, category: "cloud" },
];
