import {
  AlertCircle,
  AlertTriangle,
  Anchor,
  Archive,
  BarChart3,
  Bell,
  Bluetooth,
  Book,
  BookOpen,
  Boxes,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Camera,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudCog,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Download,
  Eye,
  EyeOff,
  Factory,
  FileSpreadsheet,
  FileText,
  Filter,
  Flag,
  Folder,
  Gift,
  GitBranch,
  GitCommit,
  GitMerge,
  Globe,
  Grid3x3,
  Hammer,
  Handshake,
  HardDrive,
  Home,
  Image as ImageIconLucide,
  Inbox,
  Info,
  Key,
  Laptop,
  Layers,
  LayoutGrid,
  LineChart,
  Link2,
  List,
  Lock,
  Map,
  MapPin,
  Mail,
  Monitor,
  Navigation,
  Package,
  Package2,
  PhoneCall,
  PieChart,
  Printer,
  RefreshCw,
  Route,
  Router,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Signal,
  SlidersHorizontal,
  Smartphone,
  Star,
  Tablet,
  Target,
  Terminal,
  Timer,
  Plane,
  Truck,
  TrendingUp,
  Unlock,
  Users,
  User,
  UserCheck,
  Warehouse,
  Webcam,
  Wifi,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

import type { IconComponent } from "../lib/iconToDataUrl";
import { AWS_SERVICE_ICONS } from "./awsServiceIcons";
import { AZURE_SERVICE_ICONS } from "./azureServiceIcons";

export interface IconAsset {
  key: string;
  label: string;
  keywords: string[];
  Icon: IconComponent;
  category: "business" | "it" | "data" | "logistics" | "general" | "cloud";
}

/** A searchable icon catalog for the Assets panel — pulled from lucide-react
 *  (the same stroke family this app's own hand-drawn icons already imitate),
 *  curated down to what's actually relevant across the diagram categories
 *  this app already has (business/it/data/project/logistics) rather than
 *  the full ~1500-icon set, which would make search noisy more than useful. */
export const ICON_CATALOG: IconAsset[] = [
  // business
  { key: "briefcase", label: "Briefcase", keywords: ["work", "job", "business"], Icon: Briefcase, category: "business" },
  { key: "building", label: "Building", keywords: ["office", "company"], Icon: Building, category: "business" },
  { key: "building-2", label: "Office tower", keywords: ["office", "hq", "headquarters"], Icon: Building2, category: "business" },
  { key: "handshake", label: "Handshake", keywords: ["deal", "partnership", "agreement"], Icon: Handshake, category: "business" },
  { key: "target", label: "Target", keywords: ["goal", "objective", "kpi"], Icon: Target, category: "business" },
  { key: "trending-up", label: "Trending up", keywords: ["growth", "chart", "sales"], Icon: TrendingUp, category: "business" },
  { key: "credit-card", label: "Payment", keywords: ["credit card", "billing", "finance"], Icon: CreditCard, category: "business" },
  { key: "users", label: "Team", keywords: ["people", "group", "users"], Icon: Users, category: "business" },
  { key: "user", label: "Person", keywords: ["user", "actor", "customer"], Icon: User, category: "business" },
  { key: "user-check", label: "Approved user", keywords: ["verified", "approved", "account"], Icon: UserCheck, category: "business" },
  { key: "calendar", label: "Calendar", keywords: ["date", "schedule", "deadline"], Icon: Calendar, category: "business" },
  { key: "clipboard-list", label: "Checklist", keywords: ["task", "todo", "requirements"], Icon: ClipboardList, category: "business" },
  { key: "clipboard-check", label: "Approved checklist", keywords: ["approved", "signoff", "audit"], Icon: ClipboardCheck, category: "business" },
  { key: "mail", label: "Email", keywords: ["mail", "message", "notification"], Icon: Mail, category: "business" },
  { key: "phone-call", label: "Phone call", keywords: ["call", "contact", "support"], Icon: PhoneCall, category: "business" },
  { key: "workflow", label: "Workflow", keywords: ["process", "pipeline", "steps"], Icon: Workflow, category: "business" },

  // it / infrastructure
  { key: "cloud", label: "Cloud", keywords: ["cloud", "saas", "hosting"], Icon: Cloud, category: "it" },
  { key: "cloud-cog", label: "Cloud service", keywords: ["cloud", "config", "iaas"], Icon: CloudCog, category: "it" },
  { key: "server", label: "Server", keywords: ["backend", "host", "compute"], Icon: Server, category: "it" },
  { key: "database", label: "Database", keywords: ["db", "storage", "sql"], Icon: Database, category: "it" },
  { key: "hard-drive", label: "Storage", keywords: ["disk", "storage", "volume"], Icon: HardDrive, category: "it" },
  { key: "cpu", label: "Processor", keywords: ["cpu", "compute", "chip"], Icon: Cpu, category: "it" },
  { key: "wifi", label: "Wi-Fi", keywords: ["network", "wireless", "internet"], Icon: Wifi, category: "it" },
  { key: "router", label: "Router", keywords: ["network", "gateway", "switch"], Icon: Router, category: "it" },
  { key: "shield", label: "Security", keywords: ["security", "protection", "firewall"], Icon: Shield, category: "it" },
  { key: "shield-check", label: "Verified security", keywords: ["compliant", "secure", "verified"], Icon: ShieldCheck, category: "it" },
  { key: "key", label: "Auth key", keywords: ["auth", "access", "credential"], Icon: Key, category: "it" },
  { key: "lock", label: "Locked", keywords: ["secure", "private", "restricted"], Icon: Lock, category: "it" },
  { key: "unlock", label: "Unlocked", keywords: ["public", "open", "access"], Icon: Unlock, category: "it" },
  { key: "terminal", label: "Terminal", keywords: ["cli", "shell", "console"], Icon: Terminal, category: "it" },
  { key: "laptop", label: "Laptop", keywords: ["device", "computer", "client"], Icon: Laptop, category: "it" },
  { key: "monitor", label: "Desktop", keywords: ["screen", "display", "workstation"], Icon: Monitor, category: "it" },
  { key: "smartphone", label: "Mobile", keywords: ["phone", "app", "device"], Icon: Smartphone, category: "it" },
  { key: "tablet", label: "Tablet", keywords: ["device", "ipad"], Icon: Tablet, category: "it" },
  { key: "printer", label: "Printer", keywords: ["print", "output", "device"], Icon: Printer, category: "it" },
  { key: "webcam", label: "Camera device", keywords: ["webcam", "video", "iot"], Icon: Webcam, category: "it" },
  { key: "bluetooth", label: "Bluetooth", keywords: ["wireless", "pairing"], Icon: Bluetooth, category: "it" },
  { key: "signal", label: "Signal", keywords: ["network", "connectivity", "strength"], Icon: Signal, category: "it" },
  { key: "refresh-cw", label: "Sync", keywords: ["sync", "refresh", "update"], Icon: RefreshCw, category: "it" },
  { key: "zap", label: "Trigger", keywords: ["event", "webhook", "automation"], Icon: Zap, category: "it" },

  // data
  { key: "bar-chart", label: "Bar chart", keywords: ["chart", "analytics", "report"], Icon: BarChart3, category: "data" },
  { key: "line-chart", label: "Line chart", keywords: ["chart", "trend", "metrics"], Icon: LineChart, category: "data" },
  { key: "pie-chart", label: "Pie chart", keywords: ["chart", "breakdown", "share"], Icon: PieChart, category: "data" },
  { key: "file-spreadsheet", label: "Spreadsheet", keywords: ["excel", "csv", "table"], Icon: FileSpreadsheet, category: "data" },
  { key: "filter", label: "Filter", keywords: ["filter", "query", "validation"], Icon: Filter, category: "data" },
  { key: "layers", label: "Layers", keywords: ["stack", "pipeline", "tiers"], Icon: Layers, category: "data" },
  { key: "git-branch", label: "Branch", keywords: ["version", "fork", "split"], Icon: GitBranch, category: "data" },
  { key: "git-merge", label: "Merge", keywords: ["merge", "combine", "join"], Icon: GitMerge, category: "data" },
  { key: "git-commit", label: "Commit", keywords: ["version", "checkpoint"], Icon: GitCommit, category: "data" },
  { key: "grid", label: "Grid", keywords: ["table", "matrix", "dataset"], Icon: Grid3x3, category: "data" },
  { key: "layout-grid", label: "Dashboard", keywords: ["dashboard", "widgets", "layout"], Icon: LayoutGrid, category: "data" },
  { key: "list", label: "List", keywords: ["list", "records", "rows"], Icon: List, category: "data" },
  { key: "sliders", label: "Controls", keywords: ["settings", "parameters", "tuning"], Icon: SlidersHorizontal, category: "data" },

  // logistics
  { key: "truck", label: "Truck", keywords: ["delivery", "freight", "transport"], Icon: Truck, category: "logistics" },
  { key: "ship", label: "Ship", keywords: ["sea freight", "cargo", "vessel"], Icon: Ship, category: "logistics" },
  { key: "plane", label: "Plane", keywords: ["air freight", "flight", "shipping"], Icon: Plane, category: "logistics" },
  { key: "package", label: "Package", keywords: ["parcel", "shipment", "box"], Icon: Package, category: "logistics" },
  { key: "package-2", label: "Crate", keywords: ["box", "cargo", "goods"], Icon: Package2, category: "logistics" },
  { key: "boxes", label: "Inventory", keywords: ["stock", "warehouse", "boxes"], Icon: Boxes, category: "logistics" },
  { key: "warehouse", label: "Warehouse", keywords: ["storage", "distribution centre"], Icon: Warehouse, category: "logistics" },
  { key: "factory", label: "Factory", keywords: ["manufacturing", "plant", "production"], Icon: Factory, category: "logistics" },
  { key: "anchor", label: "Port", keywords: ["harbour", "dock", "sea"], Icon: Anchor, category: "logistics" },
  { key: "map-pin", label: "Location", keywords: ["pin", "address", "destination"], Icon: MapPin, category: "logistics" },
  { key: "navigation", label: "Route", keywords: ["gps", "direction", "tracking"], Icon: Navigation, category: "logistics" },
  { key: "route", label: "Path", keywords: ["route", "journey", "path"], Icon: Route, category: "logistics" },
  { key: "compass", label: "Compass", keywords: ["direction", "navigation"], Icon: Compass, category: "logistics" },
  { key: "map", label: "Map", keywords: ["map", "area", "region"], Icon: Map, category: "logistics" },
  { key: "shopping-cart", label: "Order", keywords: ["cart", "purchase", "ecommerce"], Icon: ShoppingCart, category: "logistics" },

  // general / ui
  { key: "check-circle", label: "Success", keywords: ["done", "complete", "approved"], Icon: CheckCircle2, category: "general" },
  { key: "alert-triangle", label: "Warning", keywords: ["risk", "caution", "issue"], Icon: AlertTriangle, category: "general" },
  { key: "alert-circle", label: "Error", keywords: ["error", "problem", "failure"], Icon: AlertCircle, category: "general" },
  { key: "info", label: "Info", keywords: ["info", "note", "details"], Icon: Info, category: "general" },
  { key: "star", label: "Star", keywords: ["favourite", "rating", "featured"], Icon: Star, category: "general" },
  { key: "flag", label: "Flag", keywords: ["milestone", "marker", "country"], Icon: Flag, category: "general" },
  { key: "bell", label: "Notification", keywords: ["alert", "reminder", "notify"], Icon: Bell, category: "general" },
  { key: "settings", label: "Settings", keywords: ["config", "preferences", "gear"], Icon: Settings, category: "general" },
  { key: "search", label: "Search", keywords: ["find", "lookup", "query"], Icon: Search, category: "general" },
  { key: "link", label: "Link", keywords: ["url", "connection", "reference"], Icon: Link2, category: "general" },
  { key: "share", label: "Share", keywords: ["share", "distribute", "broadcast"], Icon: Share2, category: "general" },
  { key: "download", label: "Download", keywords: ["download", "export", "save"], Icon: Download, category: "general" },
  { key: "folder", label: "Folder", keywords: ["directory", "files", "storage"], Icon: Folder, category: "general" },
  { key: "archive", label: "Archive", keywords: ["archive", "storage", "backup"], Icon: Archive, category: "general" },
  { key: "inbox", label: "Inbox", keywords: ["queue", "incoming", "messages"], Icon: Inbox, category: "general" },
  { key: "send", label: "Send", keywords: ["submit", "dispatch", "outbound"], Icon: Send, category: "general" },
  { key: "globe", label: "Globe", keywords: ["global", "internet", "world"], Icon: Globe, category: "general" },
  { key: "home", label: "Home", keywords: ["home", "start", "main"], Icon: Home, category: "general" },
  { key: "gift", label: "Reward", keywords: ["gift", "reward", "incentive"], Icon: Gift, category: "general" },
  { key: "eye", label: "Visible", keywords: ["view", "visible", "show"], Icon: Eye, category: "general" },
  { key: "eye-off", label: "Hidden", keywords: ["hide", "private", "invisible"], Icon: EyeOff, category: "general" },
  { key: "clock", label: "Time", keywords: ["time", "duration", "history"], Icon: Clock, category: "general" },
  { key: "timer", label: "Timer", keywords: ["countdown", "deadline", "sla"], Icon: Timer, category: "general" },
  { key: "camera", label: "Camera", keywords: ["photo", "capture", "media"], Icon: Camera, category: "general" },
  { key: "image", label: "Image", keywords: ["picture", "photo", "media"], Icon: ImageIconLucide, category: "general" },
  { key: "file-text", label: "Document", keywords: ["file", "report", "text"], Icon: FileText, category: "general" },
  { key: "book", label: "Book", keywords: ["docs", "manual", "reference"], Icon: Book, category: "general" },
  { key: "book-open", label: "Guide", keywords: ["docs", "reading", "handbook"], Icon: BookOpen, category: "general" },
  { key: "wrench", label: "Maintenance", keywords: ["tool", "fix", "config"], Icon: Wrench, category: "general" },
  { key: "hammer", label: "Build", keywords: ["build", "construct", "tool"], Icon: Hammer, category: "general" },

  // cloud / AWS & Azure — the providers' own official architecture icons
  // (see awsServiceIcons.tsx / azureServiceIcons.tsx), so a cloud diagram can
  // name the actual managed service instead of a generic "server" or
  // "database" box. Never recoloured — that's what the providers' terms of
  // use for these icons require, and it's also why (unlike this catalog's
  // other, hand-drawn icons) these don't respond to a node's accent colour.
  { key: "aws-ec2", label: "EC2 instance", keywords: ["aws", "compute", "vm", "server"], Icon: AWS_SERVICE_ICONS["aws-ec2"], category: "cloud" },
  { key: "aws-lambda", label: "Lambda", keywords: ["aws", "serverless", "function"], Icon: AWS_SERVICE_ICONS["aws-lambda"], category: "cloud" },
  { key: "aws-ecs", label: "ECS / containers", keywords: ["aws", "docker", "container", "kubernetes"], Icon: AWS_SERVICE_ICONS["aws-ecs"], category: "cloud" },
  { key: "aws-eks", label: "Elastic Kubernetes Service", keywords: ["aws", "elastic", "kubernetes", "service", "eks"], Icon: AWS_SERVICE_ICONS["aws-eks"], category: "cloud" },
  { key: "aws-s3", label: "S3 bucket", keywords: ["aws", "storage", "bucket", "object storage"], Icon: AWS_SERVICE_ICONS["aws-s3"], category: "cloud" },
  { key: "aws-rds", label: "RDS database", keywords: ["aws", "database", "sql", "mysql", "postgres"], Icon: AWS_SERVICE_ICONS["aws-rds"], category: "cloud" },
  { key: "aws-dynamodb", label: "DynamoDB", keywords: ["aws", "nosql", "database"], Icon: AWS_SERVICE_ICONS["aws-dynamodb"], category: "cloud" },
  { key: "aws-elasticache", label: "ElastiCache / Redis", keywords: ["aws", "cache", "redis", "memcached"], Icon: AWS_SERVICE_ICONS["aws-elasticache"], category: "cloud" },
  { key: "aws-route53", label: "Route 53", keywords: ["aws", "dns", "domain", "routing"], Icon: AWS_SERVICE_ICONS["aws-route53"], category: "cloud" },
  { key: "aws-elb", label: "Load balancer", keywords: ["aws", "elb", "alb", "load balancing"], Icon: AWS_SERVICE_ICONS["aws-elb"], category: "cloud" },
  { key: "aws-cloudfront", label: "CloudFront", keywords: ["aws", "cdn", "edge", "cache"], Icon: AWS_SERVICE_ICONS["aws-cloudfront"], category: "cloud" },
  { key: "aws-api-gateway", label: "API Gateway", keywords: ["aws", "api", "rest", "gateway"], Icon: AWS_SERVICE_ICONS["aws-api-gateway"], category: "cloud" },
  { key: "aws-vpc", label: "VPC", keywords: ["aws", "network", "subnet", "vpc"], Icon: AWS_SERVICE_ICONS["aws-vpc"], category: "cloud" },
  { key: "aws-iam", label: "IAM", keywords: ["aws", "identity", "access", "permissions"], Icon: AWS_SERVICE_ICONS["aws-iam"], category: "cloud" },
  { key: "aws-sqs", label: "SQS queue", keywords: ["aws", "queue", "messaging"], Icon: AWS_SERVICE_ICONS["aws-sqs"], category: "cloud" },
  { key: "aws-sns", label: "SNS topic", keywords: ["aws", "notification", "pub/sub", "messaging"], Icon: AWS_SERVICE_ICONS["aws-sns"], category: "cloud" },
  { key: "aws-cloudwatch", label: "CloudWatch", keywords: ["aws", "monitoring", "logs", "metrics"], Icon: AWS_SERVICE_ICONS["aws-cloudwatch"], category: "cloud" },
  { key: "aws-fargate", label: "Fargate", keywords: ["aws", "fargate"], Icon: AWS_SERVICE_ICONS["aws-fargate"], category: "cloud" },
  { key: "aws-aurora", label: "Aurora", keywords: ["aws", "aurora"], Icon: AWS_SERVICE_ICONS["aws-aurora"], category: "cloud" },
  { key: "aws-step-functions", label: "Step Functions", keywords: ["aws", "step", "functions", "step functions"], Icon: AWS_SERVICE_ICONS["aws-step-functions"], category: "cloud" },
  { key: "aws-eventbridge", label: "EventBridge", keywords: ["aws", "eventbridge"], Icon: AWS_SERVICE_ICONS["aws-eventbridge"], category: "cloud" },
  { key: "aws-cloudformation", label: "CloudFormation", keywords: ["aws", "cloudformation"], Icon: AWS_SERVICE_ICONS["aws-cloudformation"], category: "cloud" },
  { key: "aws-kms", label: "Key Management Service", keywords: ["aws", "key", "management", "service", "kms"], Icon: AWS_SERVICE_ICONS["aws-kms"], category: "cloud" },
  { key: "aws-secrets-manager", label: "Secrets Manager", keywords: ["aws", "secrets", "manager", "secrets manager"], Icon: AWS_SERVICE_ICONS["aws-secrets-manager"], category: "cloud" },
  { key: "aws-waf", label: "WAF", keywords: ["aws", "waf"], Icon: AWS_SERVICE_ICONS["aws-waf"], category: "cloud" },
  { key: "aws-cognito", label: "Cognito", keywords: ["aws", "cognito"], Icon: AWS_SERVICE_ICONS["aws-cognito"], category: "cloud" },
  { key: "aws-redshift", label: "Redshift", keywords: ["aws", "redshift"], Icon: AWS_SERVICE_ICONS["aws-redshift"], category: "cloud" },
  { key: "aws-kinesis", label: "Kinesis", keywords: ["aws", "kinesis"], Icon: AWS_SERVICE_ICONS["aws-kinesis"], category: "cloud" },
  { key: "aws-glue", label: "Glue", keywords: ["aws", "glue"], Icon: AWS_SERVICE_ICONS["aws-glue"], category: "cloud" },
  { key: "aws-sagemaker", label: "SageMaker", keywords: ["aws", "sagemaker"], Icon: AWS_SERVICE_ICONS["aws-sagemaker"], category: "cloud" },
  { key: "aws-bedrock", label: "Bedrock", keywords: ["aws", "bedrock"], Icon: AWS_SERVICE_ICONS["aws-bedrock"], category: "cloud" },
  { key: "aws-auto-scaling", label: "Auto Scaling", keywords: ["aws", "auto", "scaling", "auto scaling"], Icon: AWS_SERVICE_ICONS["aws-auto-scaling"], category: "cloud" },
  { key: "aws-ebs", label: "EBS", keywords: ["aws", "ebs"], Icon: AWS_SERVICE_ICONS["aws-ebs"], category: "cloud" },
  { key: "aws-elastic-beanstalk", label: "Elastic Beanstalk", keywords: ["aws", "elastic", "beanstalk", "elastic beanstalk"], Icon: AWS_SERVICE_ICONS["aws-elastic-beanstalk"], category: "cloud" },
  { key: "aws-efs", label: "EFS", keywords: ["aws", "efs"], Icon: AWS_SERVICE_ICONS["aws-efs"], category: "cloud" },
  { key: "aws-direct-connect", label: "Direct Connect", keywords: ["aws", "direct", "connect", "direct connect"], Icon: AWS_SERVICE_ICONS["aws-direct-connect"], category: "cloud" },
  { key: "aws-transit-gateway", label: "Transit Gateway", keywords: ["aws", "transit", "gateway", "transit gateway"], Icon: AWS_SERVICE_ICONS["aws-transit-gateway"], category: "cloud" },
  { key: "aws-athena", label: "Athena", keywords: ["aws", "athena"], Icon: AWS_SERVICE_ICONS["aws-athena"], category: "cloud" },
  { key: "aws-msk", label: "Managed Streaming for Kafka", keywords: ["aws", "managed", "streaming", "for", "kafka", "msk"], Icon: AWS_SERVICE_ICONS["aws-msk"], category: "cloud" },
  { key: "aws-app-runner", label: "App Runner", keywords: ["aws", "app", "runner", "app runner"], Icon: AWS_SERVICE_ICONS["aws-app-runner"], category: "cloud" },
  { key: "aws-ecr", label: "Elastic Container Registry", keywords: ["aws", "elastic", "container", "registry", "ecr"], Icon: AWS_SERVICE_ICONS["aws-ecr"], category: "cloud" },
  { key: "az-virtual-machine", label: "Virtual Machine", keywords: ["azure", "virtual", "machine", "virtual machine"], Icon: AZURE_SERVICE_ICONS["az-virtual-machine"], category: "cloud" },
  { key: "az-function-apps", label: "Function Apps", keywords: ["azure", "function", "apps", "function apps"], Icon: AZURE_SERVICE_ICONS["az-function-apps"], category: "cloud" },
  { key: "az-app-services", label: "App Services", keywords: ["azure", "app", "services", "app services"], Icon: AZURE_SERVICE_ICONS["az-app-services"], category: "cloud" },
  { key: "az-container-instances", label: "Container Instances", keywords: ["azure", "container", "instances", "container instances"], Icon: AZURE_SERVICE_ICONS["az-container-instances"], category: "cloud" },
  { key: "az-aks", label: "Kubernetes Services (AKS)", keywords: ["azure", "kubernetes", "services", "aks"], Icon: AZURE_SERVICE_ICONS["az-aks"], category: "cloud" },
  { key: "az-storage-accounts", label: "Storage Accounts", keywords: ["azure", "storage", "accounts", "storage accounts"], Icon: AZURE_SERVICE_ICONS["az-storage-accounts"], category: "cloud" },
  { key: "az-sql-database", label: "SQL Database", keywords: ["azure", "sql", "database", "sql database"], Icon: AZURE_SERVICE_ICONS["az-sql-database"], category: "cloud" },
  { key: "az-cosmos-db", label: "Cosmos DB", keywords: ["azure", "cosmos", "db", "cosmos db"], Icon: AZURE_SERVICE_ICONS["az-cosmos-db"], category: "cloud" },
  { key: "az-cache-redis", label: "Cache for Redis", keywords: ["azure", "cache", "for", "redis", "cache redis"], Icon: AZURE_SERVICE_ICONS["az-cache-redis"], category: "cloud" },
  { key: "az-dns-zones", label: "DNS Zones", keywords: ["azure", "dns", "zones", "dns zones"], Icon: AZURE_SERVICE_ICONS["az-dns-zones"], category: "cloud" },
  { key: "az-load-balancers", label: "Load Balancers", keywords: ["azure", "load", "balancers", "load balancers"], Icon: AZURE_SERVICE_ICONS["az-load-balancers"], category: "cloud" },
  { key: "az-front-door-cdn", label: "Front Door & CDN", keywords: ["azure", "front", "door", "and", "cdn", "front door cdn"], Icon: AZURE_SERVICE_ICONS["az-front-door-cdn"], category: "cloud" },
  { key: "az-api-management", label: "API Management", keywords: ["azure", "api", "management", "api management"], Icon: AZURE_SERVICE_ICONS["az-api-management"], category: "cloud" },
  { key: "az-virtual-networks", label: "Virtual Networks", keywords: ["azure", "virtual", "networks", "virtual networks"], Icon: AZURE_SERVICE_ICONS["az-virtual-networks"], category: "cloud" },
  { key: "az-managed-identities", label: "Managed Identities", keywords: ["azure", "managed", "identities", "managed identities"], Icon: AZURE_SERVICE_ICONS["az-managed-identities"], category: "cloud" },
  { key: "az-storage-queue", label: "Storage Queue", keywords: ["azure", "storage", "queue", "storage queue"], Icon: AZURE_SERVICE_ICONS["az-storage-queue"], category: "cloud" },
  { key: "az-service-bus", label: "Service Bus", keywords: ["azure", "service", "bus", "service bus"], Icon: AZURE_SERVICE_ICONS["az-service-bus"], category: "cloud" },
  { key: "az-monitor", label: "Monitor", keywords: ["azure", "monitor"], Icon: AZURE_SERVICE_ICONS["az-monitor"], category: "cloud" },
  { key: "az-container-registries", label: "Container Registries", keywords: ["azure", "container", "registries", "container registries"], Icon: AZURE_SERVICE_ICONS["az-container-registries"], category: "cloud" },
  { key: "az-application-gateways", label: "Application Gateway", keywords: ["azure", "application", "gateway", "application gateways"], Icon: AZURE_SERVICE_ICONS["az-application-gateways"], category: "cloud" },
  { key: "az-logic-apps", label: "Logic Apps", keywords: ["azure", "logic", "apps", "logic apps"], Icon: AZURE_SERVICE_ICONS["az-logic-apps"], category: "cloud" },
  { key: "az-event-grid-topics", label: "Event Grid Topics", keywords: ["azure", "event", "grid", "topics", "event grid topics"], Icon: AZURE_SERVICE_ICONS["az-event-grid-topics"], category: "cloud" },
  { key: "az-key-vaults", label: "Key Vaults", keywords: ["azure", "key", "vaults", "key vaults"], Icon: AZURE_SERVICE_ICONS["az-key-vaults"], category: "cloud" },
  { key: "az-application-insights", label: "Application Insights", keywords: ["azure", "application", "insights", "application insights"], Icon: AZURE_SERVICE_ICONS["az-application-insights"], category: "cloud" },
  { key: "az-firewalls", label: "Firewall", keywords: ["azure", "firewall", "firewalls"], Icon: AZURE_SERVICE_ICONS["az-firewalls"], category: "cloud" },
  { key: "az-sql-data-warehouses", label: "SQL Data Warehouse", keywords: ["azure", "sql", "data", "warehouse", "sql data warehouses"], Icon: AZURE_SERVICE_ICONS["az-sql-data-warehouses"], category: "cloud" },
  { key: "az-stream-analytics", label: "Stream Analytics", keywords: ["azure", "stream", "analytics", "stream analytics"], Icon: AZURE_SERVICE_ICONS["az-stream-analytics"], category: "cloud" },
  { key: "az-data-factories", label: "Data Factory", keywords: ["azure", "data", "factory", "data factories"], Icon: AZURE_SERVICE_ICONS["az-data-factories"], category: "cloud" },
  { key: "az-machine-learning", label: "Machine Learning", keywords: ["azure", "machine", "learning", "machine learning"], Icon: AZURE_SERVICE_ICONS["az-machine-learning"], category: "cloud" },
  { key: "az-openai", label: "OpenAI Service", keywords: ["azure", "openai", "service"], Icon: AZURE_SERVICE_ICONS["az-openai"], category: "cloud" },
  { key: "az-batch-accounts", label: "Batch Accounts", keywords: ["azure", "batch", "accounts", "batch accounts"], Icon: AZURE_SERVICE_ICONS["az-batch-accounts"], category: "cloud" },
  { key: "az-disks", label: "Disks", keywords: ["azure", "disks"], Icon: AZURE_SERVICE_ICONS["az-disks"], category: "cloud" },
  { key: "az-app-service-plans", label: "App Service Plans", keywords: ["azure", "app", "service", "plans", "app service plans"], Icon: AZURE_SERVICE_ICONS["az-app-service-plans"], category: "cloud" },
  { key: "az-expressroute", label: "ExpressRoute Circuits", keywords: ["azure", "expressroute", "circuits"], Icon: AZURE_SERVICE_ICONS["az-expressroute"], category: "cloud" },
  { key: "az-traffic-manager", label: "Traffic Manager", keywords: ["azure", "traffic", "manager", "traffic manager"], Icon: AZURE_SERVICE_ICONS["az-traffic-manager"], category: "cloud" },
  { key: "az-data-lake-storage", label: "Data Lake Storage", keywords: ["azure", "data", "lake", "storage", "data lake storage"], Icon: AZURE_SERVICE_ICONS["az-data-lake-storage"], category: "cloud" },
  { key: "az-event-hubs", label: "Event Hubs", keywords: ["azure", "event", "hubs", "event hubs"], Icon: AZURE_SERVICE_ICONS["az-event-hubs"], category: "cloud" },
  { key: "az-bastions", label: "Bastion", keywords: ["azure", "bastion", "bastions"], Icon: AZURE_SERVICE_ICONS["az-bastions"], category: "cloud" },
  { key: "az-automation-accounts", label: "Automation Accounts", keywords: ["azure", "automation", "accounts", "automation accounts"], Icon: AZURE_SERVICE_ICONS["az-automation-accounts"], category: "cloud" },
];
