"""Seed the built-in template library.

    uv run python -m scripts.seed_templates

Re-running is safe: templates are upserted by slug.
"""

import asyncio

from sqlalchemy import select

from app.db.session import SessionLocal
from app.models import Template

TEMPLATES: list[dict] = [
    {
        "slug": "import-cargo-clearance",
        "name": "Import cargo clearance",
        "category": "logistics",
        "diagram_type": "swimlane",
        "description": "Documents received through to cargo release, with rejection and re-inspection loops.",
        "keywords": ["import", "cargo", "customs", "clearance", "release"],
        "data": {
            "title": "Import cargo clearance",
            "diagram_type": "swimlane",
            "direction": "LR",
            "lanes": [
                {"id": "lane_customer", "label": "Customer", "order": 0},
                {"id": "lane_ops", "label": "Operations", "order": 1},
                {"id": "lane_customs", "label": "Customs", "order": 2},
                {"id": "lane_warehouse", "label": "Warehouse", "order": 3},
            ],
            "nodes": [
                {
                    "id": "start",
                    "label": "Documents received",
                    "kind": "start",
                    "lane": "lane_customer",
                },
                {"id": "check", "label": "Check documents", "kind": "process", "lane": "lane_ops"},
                {
                    "id": "complete",
                    "label": "Documents complete?",
                    "kind": "decision",
                    "lane": "lane_ops",
                },
                {
                    "id": "request",
                    "label": "Request missing documents",
                    "kind": "process",
                    "lane": "lane_customer",
                },
                {
                    "id": "declare",
                    "label": "Submit customs declaration",
                    "kind": "document",
                    "lane": "lane_ops",
                },
                {
                    "id": "inspect",
                    "label": "Customs inspection",
                    "kind": "process",
                    "lane": "lane_customs",
                },
                {"id": "cleared", "label": "Cleared?", "kind": "decision", "lane": "lane_customs"},
                {
                    "id": "hold",
                    "label": "Hold and raise query",
                    "kind": "process",
                    "lane": "lane_customs",
                },
                {
                    "id": "release",
                    "label": "Release cargo",
                    "kind": "end",
                    "lane": "lane_warehouse",
                },
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "check"},
                {"id": "e2", "source": "check", "target": "complete"},
                {
                    "id": "e3",
                    "source": "complete",
                    "target": "request",
                    "label": "No",
                    "condition": "incomplete",
                },
                {"id": "e4", "source": "request", "target": "check", "style": "dashed"},
                {
                    "id": "e5",
                    "source": "complete",
                    "target": "declare",
                    "label": "Yes",
                    "condition": "complete",
                },
                {"id": "e6", "source": "declare", "target": "inspect"},
                {"id": "e7", "source": "inspect", "target": "cleared"},
                {
                    "id": "e8",
                    "source": "cleared",
                    "target": "hold",
                    "label": "No",
                    "condition": "rejected",
                },
                {"id": "e9", "source": "hold", "target": "inspect", "style": "dashed"},
                {
                    "id": "e10",
                    "source": "cleared",
                    "target": "release",
                    "label": "Yes",
                    "condition": "cleared",
                },
            ],
        },
    },
    {
        "slug": "approval-flow",
        "name": "Approval flow",
        "category": "business",
        "diagram_type": "process_flow",
        "description": "Request, review, approve or reject, with a rework loop.",
        "keywords": ["approval", "review", "sign off", "request"],
        "data": {
            "title": "Approval flow",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "start", "label": "Request submitted", "kind": "start"},
                {"id": "review", "label": "Review request", "kind": "process"},
                {"id": "decide", "label": "Approved?", "kind": "decision"},
                {"id": "rework", "label": "Return for changes", "kind": "process"},
                {"id": "approve", "label": "Record approval", "kind": "process"},
                {"id": "end", "label": "Request closed", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "review"},
                {"id": "e2", "source": "review", "target": "decide"},
                {"id": "e3", "source": "decide", "target": "approve", "label": "Yes"},
                {"id": "e4", "source": "decide", "target": "rework", "label": "No"},
                {"id": "e5", "source": "rework", "target": "review", "style": "dashed"},
                {"id": "e6", "source": "approve", "target": "end"},
            ],
        },
    },
    {
        "slug": "web-app-architecture",
        "name": "Web application architecture",
        "category": "it",
        "diagram_type": "architecture",
        "description": "Client, API gateway, services, cache and database tiers.",
        "keywords": ["architecture", "system", "api", "service", "database"],
        "data": {
            "title": "Web application architecture",
            "diagram_type": "architecture",
            "direction": "LR",
            "nodes": [
                {"id": "browser", "label": "Browser", "kind": "actor"},
                {"id": "cdn", "label": "CDN", "kind": "cloud"},
                {"id": "gateway", "label": "API gateway", "kind": "service"},
                {"id": "auth", "label": "Auth service", "kind": "service"},
                {"id": "core", "label": "Core API", "kind": "service"},
                {"id": "worker", "label": "Background worker", "kind": "service"},
                {"id": "queue", "label": "Job queue", "kind": "queue"},
                {"id": "cache", "label": "Redis cache", "kind": "database"},
                {"id": "db", "label": "PostgreSQL", "kind": "database"},
            ],
            "edges": [
                {"id": "e1", "source": "browser", "target": "cdn"},
                {"id": "e2", "source": "cdn", "target": "gateway"},
                {"id": "e3", "source": "gateway", "target": "auth"},
                {"id": "e4", "source": "gateway", "target": "core"},
                {"id": "e5", "source": "core", "target": "cache"},
                {"id": "e6", "source": "core", "target": "db"},
                {"id": "e7", "source": "core", "target": "queue"},
                {"id": "e8", "source": "queue", "target": "worker"},
                {"id": "e9", "source": "worker", "target": "db"},
            ],
        },
    },
    {
        "slug": "customs-declaration-platform",
        "name": "Customs declaration platform",
        "category": "it",
        "diagram_type": "architecture",
        "description": "Client tier through to data tier for a customs declaration system.",
        "keywords": ["customs", "declaration", "architecture", "platform", "tiers"],
        "data": {
            "title": "Customs declaration platform",
            "diagram_type": "architecture",
            "direction": "LR",
            "lanes": [],
            "nodes": [
                {"id": "portal", "label": "Broker portal", "kind": "actor"},
                {"id": "mobile", "label": "Mobile app", "kind": "actor"},
                {"id": "partner", "label": "Partner system", "kind": "actor"},
                {"id": "gateway", "label": "API gateway", "kind": "service"},
                {"id": "auth", "label": "Auth service", "kind": "service"},
                {"id": "declare", "label": "Declaration service", "kind": "service"},
                {"id": "inspect", "label": "Inspection service", "kind": "service"},
                {"id": "pg", "label": "PostgreSQL", "kind": "database"},
                {"id": "objects", "label": "Object storage", "kind": "database"},
                {"id": "audit", "label": "Audit log", "kind": "database"},
            ],
            "edges": [
                {"id": "e1", "source": "portal", "target": "gateway"},
                {"id": "e2", "source": "mobile", "target": "gateway"},
                {"id": "e3", "source": "partner", "target": "gateway"},
                {"id": "e4", "source": "gateway", "target": "auth"},
                {"id": "e5", "source": "gateway", "target": "declare"},
                {"id": "e6", "source": "gateway", "target": "inspect"},
                {"id": "e7", "source": "auth", "target": "pg"},
                {"id": "e8", "source": "declare", "target": "pg"},
                {"id": "e9", "source": "declare", "target": "objects"},
                {"id": "e10", "source": "inspect", "target": "objects"},
                {"id": "e11", "source": "inspect", "target": "audit", "style": "dashed"},
            ],
        },
    },
    {
        "slug": "uat-process",
        "name": "UAT process",
        "category": "project",
        "diagram_type": "swimlane",
        "description": "Test case preparation through sign-off, including defect handling.",
        "keywords": ["uat", "testing", "defect", "sign off", "acceptance"],
        "data": {
            "title": "UAT process",
            "diagram_type": "swimlane",
            "direction": "LR",
            "lanes": [
                {"id": "lane_vendor", "label": "Vendor", "order": 0},
                {"id": "lane_customer", "label": "Customer", "order": 1},
                {"id": "lane_pm", "label": "Project manager", "order": 2},
            ],
            "nodes": [
                {"id": "start", "label": "UAT scope agreed", "kind": "start", "lane": "lane_pm"},
                {
                    "id": "cases",
                    "label": "Prepare test cases",
                    "kind": "document",
                    "lane": "lane_vendor",
                },
                {
                    "id": "deploy",
                    "label": "Deploy to UAT",
                    "kind": "process",
                    "lane": "lane_vendor",
                },
                {
                    "id": "execute",
                    "label": "Execute test cases",
                    "kind": "process",
                    "lane": "lane_customer",
                },
                {
                    "id": "passed",
                    "label": "All cases passed?",
                    "kind": "decision",
                    "lane": "lane_customer",
                },
                {
                    "id": "defect",
                    "label": "Log defect",
                    "kind": "document",
                    "lane": "lane_customer",
                },
                {"id": "fix", "label": "Fix and retest", "kind": "process", "lane": "lane_vendor"},
                {"id": "signoff", "label": "Sign off UAT", "kind": "process", "lane": "lane_pm"},
                {"id": "end", "label": "Ready for go-live", "kind": "end", "lane": "lane_pm"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "cases"},
                {"id": "e2", "source": "cases", "target": "deploy"},
                {"id": "e3", "source": "deploy", "target": "execute"},
                {"id": "e4", "source": "execute", "target": "passed"},
                {"id": "e5", "source": "passed", "target": "defect", "label": "No"},
                {"id": "e6", "source": "defect", "target": "fix"},
                {"id": "e7", "source": "fix", "target": "execute", "style": "dashed"},
                {"id": "e8", "source": "passed", "target": "signoff", "label": "Yes"},
                {"id": "e9", "source": "signoff", "target": "end"},
            ],
        },
    },
    {
        "slug": "etl-pipeline",
        "name": "ETL pipeline",
        "category": "data",
        "diagram_type": "data_flow",
        "description": "Source extraction, staging, transformation, warehouse load.",
        "keywords": ["etl", "pipeline", "data", "warehouse", "ingestion"],
        "data": {
            "title": "ETL pipeline",
            "diagram_type": "data_flow",
            "direction": "LR",
            "nodes": [
                {"id": "src", "label": "Source systems", "kind": "database"},
                {"id": "extract", "label": "Extract", "kind": "process"},
                {"id": "staging", "label": "Staging area", "kind": "data"},
                {"id": "quality", "label": "Quality checks pass?", "kind": "decision"},
                {"id": "quarantine", "label": "Quarantine bad records", "kind": "data"},
                {"id": "transform", "label": "Transform", "kind": "process"},
                {"id": "load", "label": "Load to warehouse", "kind": "process"},
                {"id": "dw", "label": "Data warehouse", "kind": "database"},
            ],
            "edges": [
                {"id": "e1", "source": "src", "target": "extract"},
                {"id": "e2", "source": "extract", "target": "staging"},
                {"id": "e3", "source": "staging", "target": "quality"},
                {"id": "e4", "source": "quality", "target": "quarantine", "label": "No"},
                {"id": "e5", "source": "quality", "target": "transform", "label": "Yes"},
                {"id": "e6", "source": "transform", "target": "load"},
                {"id": "e7", "source": "load", "target": "dw"},
            ],
        },
    },
    {
        "slug": "shipment-data-pipeline",
        "name": "Shipment data pipeline",
        "category": "data",
        "diagram_type": "data_flow",
        "description": "Carrier feeds through to the warehouse, with a quarantine branch and a reprocessing loop.",
        "keywords": ["pipeline", "shipment", "ingestion", "quarantine", "quality"],
        "data": {
            "title": "Shipment data pipeline",
            "diagram_type": "data_flow",
            "direction": "LR",
            "lanes": [],
            "nodes": [
                {"id": "feeds", "label": "Carrier feeds", "kind": "database"},
                {"id": "extract", "label": "Extract", "kind": "process"},
                {"id": "staging", "label": "Staging area", "kind": "data"},
                {"id": "quality", "label": "Quality checks pass?", "kind": "decision"},
                {"id": "transform", "label": "Transform", "kind": "process"},
                {"id": "quarantine", "label": "Quarantine table", "kind": "data"},
                {"id": "warehouse", "label": "Data warehouse", "kind": "database"},
                {"id": "review", "label": "Analyst review", "kind": "actor"},
            ],
            "edges": [
                {"id": "e1", "source": "feeds", "target": "extract"},
                {"id": "e2", "source": "extract", "target": "staging"},
                {"id": "e3", "source": "staging", "target": "quality"},
                {
                    "id": "e4",
                    "source": "quality",
                    "target": "transform",
                    "label": "Yes",
                    "condition": "valid",
                },
                {
                    "id": "e5",
                    "source": "quality",
                    "target": "quarantine",
                    "label": "No",
                    "condition": "failed",
                },
                {"id": "e6", "source": "transform", "target": "warehouse"},
                {"id": "e7", "source": "quarantine", "target": "review"},
                {
                    "id": "e8",
                    "source": "review",
                    "target": "extract",
                    "label": "corrected records",
                    "style": "dashed",
                },
            ],
        },
    },
    {
        "slug": "customer-onboarding",
        "name": "Customer onboarding",
        "category": "business",
        "diagram_type": "process_flow",
        "description": "Lead through to first successful transaction, with KYC.",
        "keywords": ["onboarding", "customer", "kyc", "account"],
        "data": {
            "title": "Customer onboarding",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "start", "label": "Application received", "kind": "start"},
                {"id": "kyc", "label": "Run KYC checks", "kind": "process"},
                {"id": "pass", "label": "KYC cleared?", "kind": "decision"},
                {"id": "reject", "label": "Decline and notify", "kind": "end"},
                {"id": "account", "label": "Create account", "kind": "process"},
                {"id": "train", "label": "Onboarding session", "kind": "process"},
                {"id": "first", "label": "First transaction", "kind": "process"},
                {"id": "end", "label": "Customer active", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "kyc"},
                {"id": "e2", "source": "kyc", "target": "pass"},
                {"id": "e3", "source": "pass", "target": "reject", "label": "No"},
                {"id": "e4", "source": "pass", "target": "account", "label": "Yes"},
                {"id": "e5", "source": "account", "target": "train"},
                {"id": "e6", "source": "train", "target": "first"},
                {"id": "e7", "source": "first", "target": "end"},
            ],
        },
    },
    # ---------------------------------------------------------------- business
    {
        "slug": "sop-document-processing",
        "name": "Standard operating procedure",
        "category": "business",
        "diagram_type": "process_flow",
        "description": "A repeatable step-by-step procedure with a quality checkpoint.",
        "keywords": ["sop", "procedure", "standard", "operating", "checklist"],
        "data": {
            "title": "Standard operating procedure",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "start", "label": "Procedure triggered", "kind": "start"},
                {"id": "gather", "label": "Gather required inputs", "kind": "process"},
                {"id": "perform", "label": "Perform steps in order", "kind": "process"},
                {"id": "check", "label": "Meets quality standard?", "kind": "decision"},
                {"id": "rework", "label": "Correct and repeat", "kind": "process"},
                {"id": "record", "label": "Record completion", "kind": "document"},
                {"id": "end", "label": "Procedure complete", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "gather"},
                {"id": "e2", "source": "gather", "target": "perform"},
                {"id": "e3", "source": "perform", "target": "check"},
                {"id": "e4", "source": "check", "target": "rework", "label": "No"},
                {"id": "e5", "source": "rework", "target": "perform", "style": "dashed"},
                {"id": "e6", "source": "check", "target": "record", "label": "Yes"},
                {"id": "e7", "source": "record", "target": "end"},
            ],
        },
    },
    {
        "slug": "customer-journey-map",
        "name": "Customer journey map",
        "category": "business",
        "diagram_type": "process_flow",
        "description": "Stages a customer moves through, from first contact to advocacy.",
        "keywords": ["customer journey", "touchpoints", "experience", "lifecycle"],
        "data": {
            "title": "Customer journey map",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "aware", "label": "Awareness", "kind": "start"},
                {"id": "consider", "label": "Consideration", "kind": "process"},
                {"id": "purchase", "label": "Purchase", "kind": "process"},
                {"id": "onboard", "label": "Onboarding", "kind": "process"},
                {"id": "retain", "label": "Retention", "kind": "process"},
                {"id": "advocate", "label": "Advocacy", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "aware", "target": "consider"},
                {"id": "e2", "source": "consider", "target": "purchase"},
                {"id": "e3", "source": "purchase", "target": "onboard"},
                {"id": "e4", "source": "onboard", "target": "retain"},
                {"id": "e5", "source": "retain", "target": "advocate"},
            ],
        },
    },
    {
        "slug": "cross-team-task-workflow",
        "name": "Task workflow across teams",
        "category": "business",
        "diagram_type": "swimlane",
        "description": "A request handed between requester, approver and finance.",
        "keywords": ["workflow", "task", "approval", "cross-team", "handoff"],
        "data": {
            "title": "Task workflow across teams",
            "diagram_type": "swimlane",
            "direction": "LR",
            "lanes": [
                {"id": "lane_requester", "label": "Requester", "order": 0},
                {"id": "lane_approver", "label": "Approver", "order": 1},
                {"id": "lane_finance", "label": "Finance", "order": 2},
            ],
            "nodes": [
                {
                    "id": "start",
                    "label": "Task requested",
                    "kind": "start",
                    "lane": "lane_requester",
                },
                {
                    "id": "review",
                    "label": "Review request",
                    "kind": "process",
                    "lane": "lane_approver",
                },
                {"id": "decide", "label": "Approved?", "kind": "decision", "lane": "lane_approver"},
                {
                    "id": "declined",
                    "label": "Request declined",
                    "kind": "end",
                    "lane": "lane_requester",
                },
                {
                    "id": "budget",
                    "label": "Check budget",
                    "kind": "process",
                    "lane": "lane_finance",
                },
                {
                    "id": "pay",
                    "label": "Process payment",
                    "kind": "process",
                    "lane": "lane_finance",
                },
                {"id": "done", "label": "Task closed", "kind": "end", "lane": "lane_requester"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "review"},
                {"id": "e2", "source": "review", "target": "decide"},
                {"id": "e3", "source": "decide", "target": "declined", "label": "No"},
                {"id": "e4", "source": "decide", "target": "budget", "label": "Yes"},
                {"id": "e5", "source": "budget", "target": "pay"},
                {"id": "e6", "source": "pay", "target": "done"},
            ],
        },
    },
    # ------------------------------------------------------------- it/software
    {
        "slug": "application-architecture",
        "name": "Application architecture",
        "category": "it",
        "diagram_type": "architecture",
        "description": "Presentation, business logic and data layers of a typical app.",
        "keywords": ["application", "architecture", "layers", "tiers"],
        "data": {
            "title": "Application architecture",
            "diagram_type": "architecture",
            "direction": "LR",
            "nodes": [
                {"id": "user", "label": "User", "kind": "actor"},
                {"id": "presentation", "label": "Presentation layer", "kind": "system"},
                {"id": "business", "label": "Business logic layer", "kind": "service"},
                {"id": "data", "label": "Data layer", "kind": "database"},
                {"id": "external", "label": "External APIs", "kind": "cloud"},
            ],
            "edges": [
                {"id": "e1", "source": "user", "target": "presentation"},
                {"id": "e2", "source": "presentation", "target": "business"},
                {"id": "e3", "source": "business", "target": "data"},
                {"id": "e4", "source": "business", "target": "external"},
            ],
        },
    },
    {
        "slug": "network-diagram",
        "name": "Network diagram",
        "category": "it",
        "diagram_type": "network",
        "description": "Firewall and core switch, with the VLANs behind them.",
        "keywords": ["network", "topology", "firewall", "vlan", "switch"],
        "data": {
            "title": "Network diagram",
            "diagram_type": "network",
            "direction": "LR",
            "nodes": [
                {"id": "internet", "label": "Internet", "kind": "cloud"},
                {"id": "firewall", "label": "Firewall", "kind": "system"},
                {"id": "switch", "label": "Core switch", "kind": "system"},
                {"id": "staff", "label": "Staff VLAN", "kind": "service"},
                {"id": "servers", "label": "Server VLAN", "kind": "service"},
                {"id": "guest", "label": "Guest VLAN", "kind": "service"},
                {"id": "fileserver", "label": "File server", "kind": "database"},
            ],
            "edges": [
                {"id": "e1", "source": "internet", "target": "firewall"},
                {"id": "e2", "source": "firewall", "target": "switch"},
                {"id": "e3", "source": "switch", "target": "staff"},
                {"id": "e4", "source": "switch", "target": "servers"},
                {"id": "e5", "source": "servers", "target": "fileserver"},
                {"id": "e6", "source": "switch", "target": "guest"},
            ],
        },
    },
    {
        "slug": "api-request-flow",
        "name": "API flow",
        "category": "it",
        "diagram_type": "process_flow",
        "description": "A client request routed through the gateway, auth and a service.",
        "keywords": ["api", "request", "gateway", "flow"],
        "data": {
            "title": "API flow",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "start", "label": "Client request", "kind": "start"},
                {"id": "gateway", "label": "API gateway", "kind": "service"},
                {"id": "auth", "label": "Authenticated?", "kind": "decision"},
                {"id": "rejected", "label": "401 rejected", "kind": "end"},
                {"id": "route", "label": "Route to service", "kind": "process"},
                {"id": "handle", "label": "Service handles request", "kind": "process"},
                {"id": "end", "label": "Response returned", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "gateway"},
                {"id": "e2", "source": "gateway", "target": "auth"},
                {"id": "e3", "source": "auth", "target": "rejected", "label": "No"},
                {"id": "e4", "source": "auth", "target": "route", "label": "Yes"},
                {"id": "e5", "source": "route", "target": "handle"},
                {"id": "e6", "source": "handle", "target": "end"},
            ],
        },
    },
    {
        "slug": "sequence-user-login",
        "name": "Sequence diagram: user login",
        "category": "it",
        "diagram_type": "sequence",
        "description": "Message sequence between browser, auth service and database.",
        "keywords": ["sequence", "uml", "login", "authentication"],
        "data": {
            "title": "Sequence diagram: user login",
            "diagram_type": "sequence",
            "direction": "LR",
            "nodes": [
                {"id": "browser", "label": "Browser", "kind": "actor"},
                {"id": "auth", "label": "Auth service", "kind": "service"},
                {"id": "db", "label": "User database", "kind": "database"},
            ],
            "edges": [
                {"id": "e1", "source": "browser", "target": "auth", "label": "Submit credentials"},
                {"id": "e2", "source": "auth", "target": "db", "label": "Look up user"},
                {
                    "id": "e3",
                    "source": "db",
                    "target": "auth",
                    "label": "Return record",
                    "style": "dashed",
                },
                {
                    "id": "e4",
                    "source": "auth",
                    "target": "browser",
                    "label": "Issue token",
                    "style": "dashed",
                },
            ],
        },
    },
    # -------------------------------------------------------------------- data
    {
        "slug": "er-ecommerce",
        "name": "ER diagram: e-commerce",
        "category": "data",
        "diagram_type": "er",
        "description": "Customers, orders and products, and how they relate.",
        "keywords": ["er", "entity", "relationship", "database", "schema"],
        "data": {
            "title": "ER diagram: e-commerce",
            "diagram_type": "er",
            "direction": "LR",
            "nodes": [
                {"id": "customer", "label": "Customer", "kind": "data"},
                {"id": "order", "label": "Order", "kind": "data"},
                {"id": "order_item", "label": "Order item", "kind": "data"},
                {"id": "product", "label": "Product", "kind": "data"},
            ],
            "edges": [
                {"id": "e1", "source": "customer", "target": "order", "label": "places"},
                {"id": "e2", "source": "order", "target": "order_item", "label": "contains"},
                {"id": "e3", "source": "order_item", "target": "product", "label": "refers to"},
            ],
        },
    },
    {
        "slug": "data-flow-analytics",
        "name": "Data flow: analytics pipeline",
        "category": "data",
        "diagram_type": "data_flow",
        "description": "Event data streaming from apps into a queryable analytics store.",
        "keywords": ["streaming", "analytics", "events", "pipeline"],
        "data": {
            "title": "Data flow: analytics pipeline",
            "diagram_type": "data_flow",
            "direction": "LR",
            "nodes": [
                {"id": "app", "label": "App events", "kind": "system"},
                {"id": "stream", "label": "Event stream", "kind": "queue"},
                {"id": "processor", "label": "Stream processor", "kind": "process"},
                {"id": "store", "label": "Analytics store", "kind": "database"},
                {"id": "dashboard", "label": "Dashboard", "kind": "process"},
            ],
            "edges": [
                {"id": "e1", "source": "app", "target": "stream"},
                {"id": "e2", "source": "stream", "target": "processor"},
                {"id": "e3", "source": "processor", "target": "store"},
                {"id": "e4", "source": "store", "target": "dashboard"},
            ],
        },
    },
    {
        "slug": "data-architecture",
        "name": "Data architecture",
        "category": "data",
        "diagram_type": "architecture",
        "description": "Raw, curated and serving layers across a lake and a warehouse.",
        "keywords": ["data lake", "warehouse", "layers", "architecture"],
        "data": {
            "title": "Data architecture",
            "diagram_type": "architecture",
            "direction": "LR",
            "nodes": [
                {"id": "sources", "label": "Source systems", "kind": "database"},
                {"id": "raw", "label": "Raw zone", "kind": "data"},
                {"id": "curated", "label": "Curated zone", "kind": "data"},
                {"id": "warehouse", "label": "Data warehouse", "kind": "database"},
                {"id": "bi", "label": "BI / reporting", "kind": "service"},
            ],
            "edges": [
                {"id": "e1", "source": "sources", "target": "raw"},
                {"id": "e2", "source": "raw", "target": "curated"},
                {"id": "e3", "source": "curated", "target": "warehouse"},
                {"id": "e4", "source": "warehouse", "target": "bi"},
            ],
        },
    },
    {
        "slug": "ml-pipeline",
        "name": "ML pipeline",
        "category": "data",
        "diagram_type": "data_flow",
        "description": "From raw data to a deployed, monitored model.",
        "keywords": ["machine learning", "ml", "pipeline", "training", "deployment"],
        "data": {
            "title": "ML pipeline",
            "diagram_type": "data_flow",
            "direction": "LR",
            "nodes": [
                {"id": "raw", "label": "Raw data", "kind": "database"},
                {"id": "features", "label": "Feature engineering", "kind": "process"},
                {"id": "train", "label": "Train model", "kind": "process"},
                {"id": "check", "label": "Meets accuracy target?", "kind": "decision"},
                {"id": "tune", "label": "Tune hyperparameters", "kind": "process"},
                {"id": "deploy", "label": "Deploy model", "kind": "process"},
                {"id": "monitor", "label": "Monitor in production", "kind": "process"},
            ],
            "edges": [
                {"id": "e1", "source": "raw", "target": "features"},
                {"id": "e2", "source": "features", "target": "train"},
                {"id": "e3", "source": "train", "target": "check"},
                {"id": "e4", "source": "check", "target": "tune", "label": "No"},
                {"id": "e5", "source": "tune", "target": "train", "style": "dashed"},
                {"id": "e6", "source": "check", "target": "deploy", "label": "Yes"},
                {"id": "e7", "source": "deploy", "target": "monitor"},
            ],
        },
    },
    # ----------------------------------------------------------------- project
    {
        "slug": "project-delivery-flow",
        "name": "Project delivery flow",
        "category": "project",
        "diagram_type": "process_flow",
        "description": "Initiation through closure across a typical project lifecycle.",
        "keywords": ["project", "lifecycle", "delivery", "phases"],
        "data": {
            "title": "Project delivery flow",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "start", "label": "Project initiated", "kind": "start"},
                {"id": "plan", "label": "Plan scope and schedule", "kind": "process"},
                {"id": "execute", "label": "Execute work", "kind": "process"},
                {"id": "monitor", "label": "Monitor progress", "kind": "process"},
                {"id": "check", "label": "On track?", "kind": "decision"},
                {"id": "adjust", "label": "Adjust plan", "kind": "process"},
                {"id": "close", "label": "Close out project", "kind": "process"},
                {"id": "end", "label": "Project closed", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "plan"},
                {"id": "e2", "source": "plan", "target": "execute"},
                {"id": "e3", "source": "execute", "target": "monitor"},
                {"id": "e4", "source": "monitor", "target": "check"},
                {"id": "e5", "source": "check", "target": "adjust", "label": "No"},
                {"id": "e6", "source": "adjust", "target": "execute", "style": "dashed"},
                {"id": "e7", "source": "check", "target": "close", "label": "Yes"},
                {"id": "e8", "source": "close", "target": "end"},
            ],
        },
    },
    {
        "slug": "project-team-swimlane",
        "name": "Cross-team project swimlane",
        "category": "project",
        "diagram_type": "swimlane",
        "description": "How a deliverable moves between PM, development and QA.",
        "keywords": ["swimlane", "project", "team", "deliverable"],
        "data": {
            "title": "Cross-team project swimlane",
            "diagram_type": "swimlane",
            "direction": "LR",
            "lanes": [
                {"id": "lane_pm", "label": "Project manager", "order": 0},
                {"id": "lane_dev", "label": "Development", "order": 1},
                {"id": "lane_qa", "label": "QA", "order": 2},
            ],
            "nodes": [
                {"id": "start", "label": "Requirement defined", "kind": "start", "lane": "lane_pm"},
                {"id": "build", "label": "Build feature", "kind": "process", "lane": "lane_dev"},
                {"id": "test", "label": "Test feature", "kind": "process", "lane": "lane_qa"},
                {"id": "pass", "label": "Passes QA?", "kind": "decision", "lane": "lane_qa"},
                {"id": "fix", "label": "Fix issues", "kind": "process", "lane": "lane_dev"},
                {
                    "id": "accept",
                    "label": "Accept deliverable",
                    "kind": "process",
                    "lane": "lane_pm",
                },
                {"id": "end", "label": "Deliverable done", "kind": "end", "lane": "lane_pm"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "build"},
                {"id": "e2", "source": "build", "target": "test"},
                {"id": "e3", "source": "test", "target": "pass"},
                {"id": "e4", "source": "pass", "target": "fix", "label": "No"},
                {"id": "e5", "source": "fix", "target": "test", "style": "dashed"},
                {"id": "e6", "source": "pass", "target": "accept", "label": "Yes"},
                {"id": "e7", "source": "accept", "target": "end"},
            ],
        },
    },
    {
        "slug": "organization-chart",
        "name": "Organization chart",
        "category": "project",
        "diagram_type": "org_chart",
        "description": "Reporting lines from leadership down to individual teams.",
        "keywords": ["org chart", "hierarchy", "reporting", "structure"],
        "data": {
            "title": "Organization chart",
            "diagram_type": "org_chart",
            "direction": "TB",
            "nodes": [
                {"id": "ceo", "label": "CEO", "kind": "process"},
                {"id": "cto", "label": "CTO", "kind": "process"},
                {"id": "coo", "label": "COO", "kind": "process"},
                {"id": "eng", "label": "Engineering manager", "kind": "process"},
                {"id": "qa", "label": "QA lead", "kind": "process"},
                {"id": "ops", "label": "Operations manager", "kind": "process"},
            ],
            "edges": [
                {"id": "e1", "source": "ceo", "target": "cto"},
                {"id": "e2", "source": "ceo", "target": "coo"},
                {"id": "e3", "source": "cto", "target": "eng"},
                {"id": "e4", "source": "cto", "target": "qa"},
                {"id": "e5", "source": "coo", "target": "ops"},
            ],
        },
    },
    {
        "slug": "agile-sprint-workflow",
        "name": "Agile sprint workflow",
        "category": "project",
        "diagram_type": "process_flow",
        "description": "One sprint cycle, from backlog grooming to retrospective.",
        "keywords": ["agile", "scrum", "sprint", "workflow"],
        "data": {
            "title": "Agile sprint workflow",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "backlog", "label": "Backlog groomed", "kind": "start"},
                {"id": "planning", "label": "Sprint planning", "kind": "process"},
                {"id": "dev", "label": "Development", "kind": "process"},
                {"id": "review", "label": "Sprint review", "kind": "process"},
                {"id": "retro", "label": "Retrospective", "kind": "process"},
                {"id": "end", "label": "Sprint closed", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "backlog", "target": "planning"},
                {"id": "e2", "source": "planning", "target": "dev"},
                {"id": "e3", "source": "dev", "target": "review"},
                {"id": "e4", "source": "review", "target": "retro"},
                {"id": "e5", "source": "retro", "target": "end"},
                {
                    "id": "e6",
                    "source": "retro",
                    "target": "backlog",
                    "style": "dashed",
                    "label": "next sprint",
                },
            ],
        },
    },
    # --------------------------------------------------------------- logistics
    {
        "slug": "export-process",
        "name": "Export process",
        "category": "logistics",
        "diagram_type": "swimlane",
        "description": "Export documentation, customs clearance and loading for departure.",
        "keywords": ["export", "shipping", "customs", "documentation"],
        "data": {
            "title": "Export process",
            "diagram_type": "swimlane",
            "direction": "LR",
            "lanes": [
                {"id": "lane_exporter", "label": "Exporter", "order": 0},
                {"id": "lane_customs", "label": "Customs", "order": 1},
                {"id": "lane_carrier", "label": "Carrier", "order": 2},
            ],
            "nodes": [
                {
                    "id": "start",
                    "label": "Booking confirmed",
                    "kind": "start",
                    "lane": "lane_exporter",
                },
                {
                    "id": "docs",
                    "label": "Prepare export documents",
                    "kind": "document",
                    "lane": "lane_exporter",
                },
                {
                    "id": "declare",
                    "label": "Submit customs declaration",
                    "kind": "process",
                    "lane": "lane_exporter",
                },
                {
                    "id": "cleared",
                    "label": "Cleared for export?",
                    "kind": "decision",
                    "lane": "lane_customs",
                },
                {
                    "id": "hold",
                    "label": "Hold for review",
                    "kind": "process",
                    "lane": "lane_customs",
                },
                {"id": "load", "label": "Load cargo", "kind": "process", "lane": "lane_carrier"},
                {"id": "end", "label": "Vessel departed", "kind": "end", "lane": "lane_carrier"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "docs"},
                {"id": "e2", "source": "docs", "target": "declare"},
                {"id": "e3", "source": "declare", "target": "cleared"},
                {"id": "e4", "source": "cleared", "target": "hold", "label": "No"},
                {"id": "e5", "source": "hold", "target": "declare", "style": "dashed"},
                {"id": "e6", "source": "cleared", "target": "load", "label": "Yes"},
                {"id": "e7", "source": "load", "target": "end"},
            ],
        },
    },
    {
        "slug": "warehouse-operations-flow",
        "name": "Warehouse operations flow",
        "category": "logistics",
        "diagram_type": "process_flow",
        "description": "Inbound receiving through to outbound shipping.",
        "keywords": ["warehouse", "receiving", "picking", "packing", "shipping"],
        "data": {
            "title": "Warehouse operations flow",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "start", "label": "Goods received", "kind": "start"},
                {"id": "inspect", "label": "Inspect and check-in", "kind": "process"},
                {"id": "putaway", "label": "Put away stock", "kind": "process"},
                {"id": "pick", "label": "Pick order", "kind": "process"},
                {"id": "pack", "label": "Pack order", "kind": "process"},
                {"id": "ship", "label": "Ship order", "kind": "process"},
                {"id": "end", "label": "Order shipped", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "inspect"},
                {"id": "e2", "source": "inspect", "target": "putaway"},
                {"id": "e3", "source": "putaway", "target": "pick"},
                {"id": "e4", "source": "pick", "target": "pack"},
                {"id": "e5", "source": "pack", "target": "ship"},
                {"id": "e6", "source": "ship", "target": "end"},
            ],
        },
    },
    {
        "slug": "delivery-last-mile",
        "name": "Delivery and last-mile flow",
        "category": "logistics",
        "diagram_type": "process_flow",
        "description": "Dispatch through delivery, with a failed-attempt path.",
        "keywords": ["delivery", "last mile", "dispatch", "logistics"],
        "data": {
            "title": "Delivery and last-mile flow",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "start", "label": "Order dispatched", "kind": "start"},
                {"id": "transit", "label": "Out for delivery", "kind": "process"},
                {"id": "check", "label": "Delivered successfully?", "kind": "decision"},
                {"id": "log", "label": "Log failed attempt", "kind": "process"},
                {"id": "reschedule", "label": "Reschedule delivery", "kind": "process"},
                {"id": "end", "label": "Delivered", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "transit"},
                {"id": "e2", "source": "transit", "target": "check"},
                {"id": "e3", "source": "check", "target": "log", "label": "No"},
                {"id": "e4", "source": "log", "target": "reschedule"},
                {"id": "e5", "source": "reschedule", "target": "transit", "style": "dashed"},
                {"id": "e6", "source": "check", "target": "end", "label": "Yes"},
            ],
        },
    },
    {
        "slug": "cargo-tracking-flow",
        "name": "Cargo tracking flow",
        "category": "logistics",
        "diagram_type": "process_flow",
        "description": "Cargo movement from origin port to final delivery, with customs.",
        "keywords": ["cargo", "tracking", "port", "shipment"],
        "data": {
            "title": "Cargo tracking flow",
            "diagram_type": "process_flow",
            "direction": "LR",
            "nodes": [
                {"id": "start", "label": "Cargo at origin port", "kind": "start"},
                {"id": "loaded", "label": "Loaded on vessel", "kind": "process"},
                {"id": "transit", "label": "In transit", "kind": "process"},
                {"id": "arrived", "label": "Arrived at destination port", "kind": "process"},
                {"id": "customs", "label": "Customs clearance", "kind": "process"},
                {"id": "delivery", "label": "Final delivery", "kind": "process"},
                {"id": "end", "label": "Delivered", "kind": "end"},
            ],
            "edges": [
                {"id": "e1", "source": "start", "target": "loaded"},
                {"id": "e2", "source": "loaded", "target": "transit"},
                {"id": "e3", "source": "transit", "target": "arrived"},
                {"id": "e4", "source": "arrived", "target": "customs"},
                {"id": "e5", "source": "customs", "target": "delivery"},
                {"id": "e6", "source": "delivery", "target": "end"},
            ],
        },
    },
]


async def main() -> None:
    async with SessionLocal() as db:
        for spec in TEMPLATES:
            existing = (
                await db.execute(select(Template).where(Template.slug == spec["slug"]))
            ).scalar_one_or_none()
            if existing:
                for key, value in spec.items():
                    setattr(existing, key, value)
                print(f"updated  {spec['slug']}")
            else:
                db.add(Template(**spec, is_builtin=True))
                print(f"inserted {spec['slug']}")
        await db.commit()
    print(f"\n{len(TEMPLATES)} templates ready.")


if __name__ == "__main__":
    asyncio.run(main())
